### ISSUE TITLE
how can I save the modified data if I change the icons layout?

### ISSUE THREAD

**Issue by eity0323** [coderitual/jtop#1]
how can I save the modified data if I change the icons layout?

**Comment by coderitual** [comment]
Unfortunately in the demo page you cannot. A websire which used this library has been using backend server for persisting data. Perhabs some local storage/session storage could be used for demonstration purpose. This library is quite old but any contribution would be appreciated.

**Comment by eity0323** [comment]
I have found the way to get them.I got them from desktop.items, like this:

`

var res = "[";
var node = null;
var haschild = false;
for (var key in desktop.items) { 
	node = desktop.items[key];
	if (node.type == "PANEL") {
		res += "{'type':'" + node.type + "','gridh':" + node.settings.height + ",'gridw':" + node.settings.width + ",'title':'" + node.settings.title + "'";
		if (node.grid._grid) {
			var subnode = null;
			var hassubchild = false;
			if (node.grid._grid.length) {
				res += ",sub:["
			}
			for (var i = 0, j = node.grid._grid.length; i < j; i++) {
				subnode = node.grid._grid[i];
				if (subnode) {
					for (var m = 0, n = subnode.length; m < n; m++) {
						if (subnode[m] && subnode[m].length > 0) {
							subnode[m].forEach(function(value, index, array) {
								res += "{'type':'" + value.type + "','gridx':" + value.settings.gridX + ",'gridy':" + value.settings.gridY + ",'title':'" + value.settings.title + "'},";
							}, this);
							hassubchild = true;
						}
					}
				}
			}
			if (hassubchild) {
				res = res.substr(0, res.length - 1);
			}
			if (node.grid._grid.length) {
				res += "]"
			}
		}
		res += "},";
	} else {
		res += "{'type':'" + node.type + "','gridx':" + node.settings.gridX + ",'gridy':" + node.settings.gridY + ",'title':'" + node.settings.title + "'},";
	}
	haschild = true;
}
if (haschild) {
	res = res.substr(0, res.length - 1);
}
res += "]"
console.log("res: " + res);

`

**Comment by coderitual** [comment]
ok :)
